# Generated by Django 4.2.2 on 2023-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(verbose_name='Минимальное значение')),
                ('max_value', models.FloatField(verbose_name='Максимальное значение')),
                ('color', models.CharField(help_text='Код цвета в HEX формате', verbose_name='Код цвета')),
            ],
            options={
                'verbose_name': 'Интервал рейтинга',
                'verbose_name_plural': 'Интервалы рейтинга',
            },
        ),
    ]
