# Generated by Django 4.2.2 on 2023-07-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_ratingrange_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingrange',
            name='text_color',
            field=models.CharField(default='000000', help_text='Код цвета текста в HEX формате', verbose_name='Код цвета текста'),
        ),
        migrations.AlterField(
            model_name='ratingrange',
            name='color',
            field=models.CharField(help_text='Код цвета фона в HEX формате', verbose_name='Код цвета фона'),
        ),
    ]
