# Generated by Django 4.2.2 on 2023-06-15 19:22

import bonkombinezon_otk.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Фамилия Имя Отчество')),
                ('barcode', models.CharField(max_length=128, verbose_name='Штрихкод')),
            ],
            bases=(bonkombinezon_otk.utils.CustomStr, models.Model),
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы товаров')),
                ('amount', models.IntegerField(verbose_name='Плата за изделие')),
            ],
            bases=(bonkombinezon_otk.utils.CustomStr, models.Model),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название изделия')),
                ('barcode', models.CharField(max_length=128, verbose_name='Штрихкод изделия')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='otk.productcategories', verbose_name='Группа товаров')),
            ],
            bases=(bonkombinezon_otk.utils.CustomStr, models.Model),
        ),
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_date', models.DateTimeField(auto_now=True, verbose_name='Дата приемки')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='otk.employees', verbose_name='Сотрудник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='otk.products', verbose_name='Товар')),
            ],
            bases=(bonkombinezon_otk.utils.CustomStr, models.Model),
        ),
    ]
