# Generated by Django 4.2.2 on 2023-06-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
