# Generated by Django 4.2.2 on 2023-06-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0003_alter_acceptance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='amount',
            field=models.IntegerField(blank=True, verbose_name='Плата за изделие'),
        ),
    ]
