# Generated by Django 4.2.2 on 2023-06-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0004_alter_productcategories_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Плата за изделие'),
        ),
    ]
