# Generated by Django 4.2.2 on 2023-06-17 13:59

from django.db import migrations, models
import otk.models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0005_alter_productcategories_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='acceptance_date',
            field=models.DateTimeField(default=otk.models.default_datetime, verbose_name='Дата приемки'),
        ),
    ]
